### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Borewit** [CodeF0x/violin#126]
**Describe the bug**
Installing the dependencies using `npm install` throws an error `sh: electron-builder: command not found`

**To Reproduce**
Check out the repository
Run:
```sh
npm install
```

**Expected behavior**

**Screenshots**
If it's an UI problem, please include a screenshot.

**Desktop (please complete the following information):**
 - OS: Linux, Fedora
 - Version: master https://github.com/CodeF0x/violin/commit/33e19cb7bcf384d3d21e5f8087fb26b65cb68655

**Additional context**
Will submit a PR: #127

**Comment by CodeF0x** [comment]
Thanks for submitting this issue! I'll have a look when I am back from holiday.
